### ISSUE TITLE
[RFC #0102] - Image history metadata

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#214]
[RFC #0102](https://github.com/buildpacks/rfcs/blob/main/text/0102-history.md) - Image history metadata

Spec:
- [x] https://github.com/buildpacks/spec/issues/299
- [x] Released in platform API version `0.12`

Lifecycle:
- [x] https://github.com/buildpacks/lifecycle/issues/411
- [x] Released in lifecycle version `0.17.0`

**Comment by edmorley** [comment]
The first item in the Lifecycle todo list above links to a duped issue, so is showing as completed, but that's just because it was closed out as a dupe. Could you update that item to https://github.com/buildpacks/lifecycle/issues/411 instead? :-)

**Comment by natalieparellano** [comment]
Thanks @edmorley !

**Comment by jjbustamante** [comment]
@natalieparellano I think we can close this issue,right?

**Comment by natalieparellano** [comment]
I think so :) Thanks @jjbustamante for noticing this
