### ISSUE TITLE
[RFC #0096] Remove Stacks and Mixins

### ISSUE THREAD

**Issue by jromero** [buildpacks/rfcs#219]
[RFC #0096](https://github.com/buildpacks/rfcs/blob/main/text/0096-remove-stacks-mixins.md) - Remove Stacks & Mixins

Spec:
- [ ] https://github.com/buildpacks/spec/issues/258
- [ ] https://github.com/buildpacks/spec/issues/259
- [ ] https://github.com/buildpacks/spec/issues/260
- [ ] https://github.com/buildpacks/spec/pull/266
- [ ] Released in `<placeholder>`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/742
- [ ] https://github.com/buildpacks/lifecycle/issues/743
- [ ] https://github.com/buildpacks/lifecycle/issues/744
- [ ] Released in `<placeholder>`

Libcnb:
- TBD

Pack:
- [ ] https://github.com/buildpacks/pack/issues/1303
- [ ] https://github.com/buildpacks/pack/issues/1302
- [ ] https://github.com/buildpacks/pack/issues/1301
- [ ] Released in `<placeholder>`

Samples:
- [ ] https://github.com/buildpacks/samples/issues/111
- [ ] Released in `<placeholder>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/422
- [ ] Released in `<placeholder>`

**Comment by jkutner** [comment]
Jesse will probably be out of pocket for a while. If anyone else is interested in moving these forward, please help :)

**Comment by ekcasey** [comment]
The high levels concerns I have here are around:
1. Migration Path
2. API orthogonality
3. Platform/Builder/Stack/Lifecycle compatibility matrix

Here are the outstanding questions I think we need answers to:

1. There are some existing places where the lifecycle reads run-image labels (example: [lifecycle reads](https://github.com/buildpacks/lifecycle/blob/main/rebaser.go#L38) `io.buildpacks.stack.id` during rebase) and newly proposed instances (e.g. [analyzer reads `io.builldpacks.id`](https://github.com/buildpacks/lifecycle/issues/742)). If we define these labels in the distribution API instead of the platform API:
  a) Must the lifecycle express [compatibility](https://github.com/buildpacks/lifecycle#supported-apis) with various Distribution APIs, in addition to platform and buildpack APIs?
  b) If not, why not? Should the platform provide consistently formatted inputs instead?
  
 1. We are requiring platform API environment variable inputs like `CNB_LAYERS_DIR` or the schema of `order.toml` to be set on builder images, but what happens when the platform API changes, for example renaming one of these variables?
 a) Can an older builder still be used with this new platform API? If so, how does that work (e.g. does the platform handle the translation?)?
 b) Can a builder implementing a newer distribution API still be used with older platforms? If so, how does that work? If no, must platforms express which distributions APIs they support?
 
 1. Can I rebase an app image built with an older stack onto a newer stack that only specifies the newer limited set of metadata (i'm leaning yes)? Does this require `--force` (less sure about this one)? What about downgrades to older stack APIs?
 
 1. Can I run a newer buildpack that only specifies `targets` on an older stack (with a stack ID and mixins)? If so, who sets the new required env variables like `CNB_TARGET_DISTRO_NAME (lifecycle could probably do this successfully for linux given `/etc/os-release` and assuming stack ID -> target ID)? If not, can the buildpack specify both stack and targets to achieve compatibility?
 
 1. Can I make a distribution 0.3 builder from an older stack?
 
 1. Can I combine buildpacks implementing different distribution APIs onto a builder? What is its version? In that case does I am assuming the platform creating the builder handles any migration (e.g. labels)?
 
 1. As a stack author what exactly do I need to do to support both old and new buildpacks? old and new platforms? Do I need to indicate somehow that I intend to provide backwards compatibility?

**Comment by schneems** [comment]
> Migration Path

I'm curious about this as well. We use stack ID for layer invalidation for layers that may contain natively compiled code (like `bundle install` can install C extensions that depend on the current system.

**Comment by jabrown85** [comment]
> > Migration Path
> 
> I'm curious about this as well. We use stack ID for layer invalidation for layers that may contain natively compiled code (like `bundle install` can install C extensions that depend on the current system.

There are [new values](https://github.com/buildpacks/lifecycle/issues/743) that buildpacks will have available to help determine layer compatibility. For your case, I think your buildpacks go from checking `heroku-22` to making sure `CNB_TARGET_DISTRO_NAME` and friends are all the same before using the cache.

Does that help answer your question @schneems ?
