### ISSUE TITLE
[RFC #0119] - Export to OCI format

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/rfcs#237]
[RFC #203](https://github.com/buildpacks/rfcs/blob/main/text/0119-export-to-oci.md) - Export to OCI format

# Phase 1

The goal for this phase is to deliver an experimental version of the feature, wait for the community to use it and gives feedback to keep improving it

### Spec
- [x] https://github.com/buildpacks/spec/issues/327
- [x] Released in platform API version `0.12`

### Imgutil
- [x] https://github.com/buildpacks/imgutil/issues/162
- [x] https://github.com/buildpacks/imgutil/issues/168
- [x] https://github.com/buildpacks/imgutil/issues/174
- [x] https://github.com/buildpacks/imgutil/issues/179

### Lifecycle
- [x] https://github.com/buildpacks/lifecycle/issues/953
- [x] Released in lifecycle version `0.17.0`
- [x] https://github.com/buildpacks/lifecycle/issues/1194
- [x] Released in lifecycle version `0.17.1`

### Pack:
- [x] https://github.com/buildpacks/pack/issues/1548
- [x] Released in pack version `0.30.0`
- [x] https://github.com/buildpacks/pack/issues/1881
- [x] Released in pack version `0.30.1`

### Documentation:
- [x] https://github.com/buildpacks/docs/issues/529

# Phase 2

The initial idea of this phase was to work in the `rebase` capability in pack for an Image exported on disk in OCI layout format, we are not sure if this is useful and if it worth it. We would like to hear from the community if this is something valuable to work on

### Imgutil
- [ ] https://github.com/buildpacks/imgutil/issues/170

### Lifecycle
- [x] https://github.com/buildpacks/lifecycle/issues/957
- [ ] Released in lifecycle version `TBD`

**Comment by jjbustamante** [comment]
Yes! we can close it. We decided not to move forward with phase 2
