### ISSUE TITLE
[RFC #0112] - Lifecycle / Launcher SBOM

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#245]
[RFC #0112](https://github.com/buildpacks/rfcs/blob/main/text/0112-launcher-sbom.md) - Lifecycle / Launcher SBOM

Spec:
- [x] https://github.com/buildpacks/spec/pull/332
- [x] Released in platform API version `0.11`

Lifecycle:
- [x] https://github.com/buildpacks/lifecycle/issues/958
- [x] Released in lifecycle version `0.16`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD

**Comment by natalieparellano** [comment]
Closing as completed
