### ISSUE TITLE
[RFC #0111] - Insecure registries

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#246]
[RFC #0111](https://github.com/buildpacks/rfcs/blob/main/text/text/0111-support-insecure-registries.md) - Insecure registries

Spec:
- [ ] https://github.com/buildpacks/spec/issues/TBD
- [ ] Released in platform API version `TBD`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/TBD
- [ ] Released in lifecycle version `TBD`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/TBD
- [ ] Released in pack version `TBD`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD

**Comment by natalieparellano** [comment]
@wanjunlei would you like me to assign you this issue?

**Comment by cmoulliard** [comment]
What is the status of this RFC ? @natalieparellano

**Comment by natalieparellano** [comment]
@cmoulliard I believe it's just waiting to be implemented. @wanjunlei were you able to pick this up?

**Comment by dlion** [comment]
Hi @natalieparellano I'd like to work on this RFC if @wanjunlei didn't have the time to do so :)

**Comment by wanjunlei** [comment]
Sorry, I don't have time to work on this feature at the moment, it would be great if you could.

**Comment by dlion** [comment]
Hey @natalieparellano , I created [the issue on spec](https://github.com/buildpacks/spec/issues/364), can you update the tracking issue please?

**Comment by cmoulliard** [comment]
Do we know when this new feature supporting insecure registry will be released (lifecycle, etc) ? @natalieparellano

**Comment by dlion** [comment]
Hey @natalieparellano, can you update this issue with the pack's issue I just opened? 
https://github.com/buildpacks/pack/issues/1916
Thanks

**Comment by dlion** [comment]
@natalieparellano Also I thought about the documentation issue, I think that the documentation will be automatically updated whenever we ship lifecycle, right? (I'm talking about the parameter and the description).
Is there other places where we need to update the doc? (if there is a way to do so)
