### ISSUE TITLE
[RFC #0107] - `pack buildpack new` alternatives

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#247]
[RFC #0107](https://github.com/buildpacks/rfcs/blob/main/text/text/0107-pack-buildpack-new-alternatives.md) - `pack buildpack new` alternatives

Pack:
- [ ] https://github.com/buildpacks/pack/pull/1534
- [ ] Released in pack version `TBD`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD

cc @AidanDelaney

**Comment by AidanDelaney** [comment]
I need to make a release of https://github.com/buildpacks/scafall then we can use it in `pack`.
