### ISSUE TITLE
[RFC #0109] - Builder config

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#248]
[RFC #0109](https://github.com/buildpacks/rfcs/blob/main/text/text/0109-build-config.md) - Builder config

Spec:
- [ ] https://github.com/buildpacks/spec/issues/TBD
- [ ] Released in <INSERT API - e.g., platform> API version `0.11`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/pull/962
- [ ] Released in lifecycle version `0.16`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD

cc @samj1912 @AidanDelaney
