### ISSUE TITLE
[RFC #0110] - Deprecate APIs

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#249]
[RFC #0110](https://github.com/buildpacks/rfcs/blob/main/text/0110-deprecate-apis.md) - Deprecate APIs

Spec:
- [x] buildpack/0.X and platform/0.X branches of github.com/buildpacks/spec marked deprecated

Lifecycle:
- [x] Older APIs marked deprecated in lifecycle version `0.16`
- [x] Older APIs removed in lifecycle version `0.18`
