### ISSUE TITLE
[RFC #0066] - Pre-release APIs and experimental features

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#251]
[RFC #0066](https://github.com/buildpacks/rfcs/blob/main/text/0066-lifecycle-prelease-version-and-experimental-section.md) - Pre-release APIs and experimental features

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/pull/864
- [ ] Released in lifecycle version `0.15.0`

Pack:
- [ ] https://github.com/buildpacks/pack/pull/1478
- [ ] Released in pack version `0.28.0`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD

**Comment by natalieparellano** [comment]
We think pre-release APIs will become more useful as we approach 1.0
