### ISSUE TITLE
[RFC #0040] - Export report

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#252]
[RFC #0040](https://github.com/buildpacks/rfcs/blob/main/text/text/0040-export-report.md) - Export report

Spec:
- [x] Released in platform API version `0.40`

Lifecycle:
- [x] Released in lifecycle version `0.9.0`

Pack:
- [x] https://github.com/buildpacks/pack/issues/1221
- [x] Released in pack version `0.29.0`

Documentation:
- [x] https://github.com/buildpacks/docs/issues/TBD

**Comment by natalieparellano** [comment]
This is done but just needs to be documented. @joe-kimmel-vmw as the pack implementor, would you be up for taking this on?

**Comment by joe-kimmel-vmw** [comment]
@natalieparellano - - I went through the docs pages trying to think where it would be useful to specify this but nothing jumped out at me.  

IIRC at the time I was implementing it I thought maybe it was sufficient that it appears in the (auto-generated) [CLI docs](https://buildpacks.io/docs/tools/pack/cli/pack_build/).  

Where do you think other docs for this feature belong?

**Comment by natalieparellano** [comment]
Sounds good to me, if you think we can close this out let's go ahead :)

**Comment by joe-kimmel-vmw** [comment]
ok, sounds like it's done enough to close! :)
