### ISSUE TITLE
[RFC #0113] - Additional OCI artifacts

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#260]
[RFC #0113](https://github.com/buildpacks/rfcs/blob/main/text/0113-additonal-oci-artifacts.md) - Additional OCI artifacts

Spec:
- [ ] https://github.com/buildpacks/spec/issues/TBD
- [ ] Released in platform API version `TBD`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/TBD
- [ ] Released in lifecycle version `TBD`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/TBD
- [ ] Released in pack version `TBD`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/TBD
