### ISSUE TITLE
[RFC #0116] - Stop deleting cache images

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#268]
[RFC #0116](https://github.com/buildpacks/rfcs/blob/main/text/XXX) - Stop deleting cache images

Lifecycle:
- [x] https://github.com/buildpacks/lifecycle/issues/803
- [ ] Released in lifecycle version `<TBD>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/551

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.

**Comment by dlion** [comment]
Hi @natalieparellano, I'd like to pick this up 🧑🏻‍💻

**Comment by natalieparellano** [comment]
Thanks @dlion! I'll assign you :)

**Comment by dlion** [comment]
* Lifecycle PR: https://github.com/buildpacks/lifecycle/pull/1136
* Documentation PR: https://github.com/buildpacks/docs/pull/594
