### ISSUE TITLE
[RFC #0078] - Group additions to builder order

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/rfcs#276]
[RFC #0078](https://github.com/buildpacks/rfcs/blob/main/text/0078-group-additions.md) - Group additions to builder order

Spec:
- [ ] https://github.com/buildpacks/spec/pull/233
- [ ] Released in Project Descriptor API version `0.2`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/<INSERT ISSUE NUMBER> (project.toml)
- [ ] https://github.com/buildpacks/pack/pull/1621 (flags)
- [ ] Released in pack version `<placeholder>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/<INSERT ISSUE NUMBER>

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.
