### ISSUE TITLE
[RFC #000>] - Multi-arch support in CNB Ecosystem

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/rfcs#294]
[RFC #<INSERT RFC NUMBER - e.g., 0099>](https://github.com/buildpacks/rfcs/blob/main/text/<INSERT FILENAME>) - <INSERT RFC TITLE>

Spec:
- [ ] https://github.com/buildpacks/spec/issues/<INSERT ISSUE NUMBER>
- [ ] Released in <INSERT API - e.g., platform> API version `<placeholder>`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/<INSERT ISSUE NUMBER>
- [ ] Released in lifecycle version `<placeholder>`

Libcnb:
- [ ] https://github.com/buildpacks/libcnb/issues/<INSERT ISSUE NUMBER>
- [ ] Released in libcnb version `<placeholder>`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/<INSERT ISSUE NUMBER>
- [ ] Released in pack version `<placeholder>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/<INSERT ISSUE NUMBER>

<INSERT OTHER REPO>:
- [ ] <INSERT ISSUE URL>
- [ ] Released in <INSERT COMPONENT> version `<placeholder>`

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.

**Comment by vnobo** [comment]
good job

**Comment by zs-dima** [comment]
+1 ARM64 is very much in demand

**Comment by jjbustamante** [comment]
## Update - 05/31/2024

- We just released pack `0.34.0`, this new version included **phase 1** and **phase 2** capabilities
- [Paketo](https://paketo.io/) already published their [jammy buildpackless builder](https://github.com/paketo-buildpacks/builder-jammy-buildpackless-static), and their Java buildpacks  for `amd64` and `arm64` architectures. They are working very hard for support and test their other buildpacks. 
- Other buildpack authors like Google and Heroku will probably do the same thing.

Again, the problem of supporting multi-platform can't be solved in just one place, all the components need to be available for multi-platform, but pack `0.34.0` was a big win on that direction.
