### ISSUE TITLE
[RFC #0129] - Export Run Image Metadata

### ISSUE THREAD

**Issue by jabrown85** [buildpacks/rfcs#315]
[RFC #313 ](https://github.com/buildpacks/rfcs/blob/main/text/0129-export-run-image-metadata.md) - Export Run Image Metadata

Spec:
- [ ] https://github.com/buildpacks/spec/issues/409
- [ ] Released in <INSERT API - e.g., platform> API version `<placeholder>`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/1372
- [ ] Released in lifecycle version `<placeholder>`

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.
