### ISSUE TITLE
[RFC #0130] OCI Image annotations

### ISSUE THREAD

**Issue by jkutner** [buildpacks/rfcs#318]
[RFC #0130](https://github.com/buildpacks/rfcs/blob/main/text/0130-oci-image-annotations.md) - OCI Image annotations

Spec:
- [ ] https://github.com/buildpacks/spec/issues/<INSERT ISSUE NUMBER>
- [ ] Released in <INSERT API - e.g., platform> API version `<placeholder>`

Lifecycle:
- [ ] https://github.com/buildpacks/lifecycle/issues/<INSERT ISSUE NUMBER>
- [ ] Released in lifecycle version `<placeholder>`

Libcnb:
- [ ] https://github.com/buildpacks/libcnb/issues/<INSERT ISSUE NUMBER>
- [ ] Released in libcnb version `<placeholder>`

Pack:
- [ ] https://github.com/buildpacks/pack/issues/<INSERT ISSUE NUMBER>
- [ ] Released in pack version `<placeholder>`

Documentation:
- [ ] https://github.com/buildpacks/docs/issues/<INSERT ISSUE NUMBER>

<INSERT OTHER REPO>:
- [ ] <INSERT ISSUE URL>
- [ ] Released in <INSERT COMPONENT> version `<placeholder>`

**Maintainers**: when closing this issue as completed, submit a PR to update the `Status` of the RFC to `Implemented`.
